### ISSUE TITLE
Informational rather than issue

### ISSUE THREAD

**Issue by rragan** [STRML/node-toobusy#2]
Before switching from the C++ tooBusy version, I wanted to understand the performance of this JS version. I ran timing tests using process.hrtime and observed that the JS version was 2-3x faster than the native version. I assume this is probably due to context switch costs for c++.

As a side effect, installs are much faster.

Thanks for this.

**Comment by asilvas** [comment]
The task is very lightweight and periodic, so performance is a non factor

**Comment by rragan** [comment]
Yep, not worried about that really but wanted to check. For us, the C++ version was causing build problems with node 0.11 and with iojs so going to a JS version made those go away (plus speed up installs).
