### ISSUE TITLE
Don't call `start()` when importing module

### ISSUE THREAD

**Issue by robross0606** [STRML/node-toobusy#26]
It is a bit of a code smell to invoke `state()` the second someone imports the module.  It makes the library lest testable and controllable.  Allow users to import the module and then call `start()` and `shutdown()` as they desire.

**Comment by robross0606** [comment]
`start()` is also called every time `interval()` is called, which means you're creating an interval, probably killing it, and creating a new one just because one is created when the module is imported.

**Comment by robross0606** [comment]
Also, why is interval capped at 16ms?

**Comment by rickfero** [comment]
> Also, why is interval capped at 16ms?

I'm pretty sure this project is dead and incredibly out of date. Don't use it.

**Comment by robross0606** [comment]
@rickfero, thank you for the candid advice. I was attracted to the smoothing algorithms in this project. Short of using `perf_hooks` which has its own issues, do you know of a good replacement?

**Comment by rickfero** [comment]
No sorry, I don't think there are any working libraries now.  The various too-busy libraries from 10 years ago never worked well including this one.

**Comment by robross0606** [comment]
What about ones not based on too-busy at all?  Something completely different?

**Comment by rickfero** [comment]
Sorry, I don't know.     ask  https://www.reddit.com/r/node/

**Comment by robross0606** [comment]
Okay, thanks for the info.

**Comment by STRML** [comment]
I'd ask what your needs are. Interval is not allowed to be less than 16ms because (at the time) it was generally not possible to get reliable results that quickly. 

I agree that start() should not be invoked at import. Changing it would be breaking, of course. But you could work around this by immediately calling shutdown(), then interval().
