### ISSUE TITLE
start() never called unless interval is explicitly set

### ISSUE THREAD

**Issue by cruisercohen** [STRML/node-toobusy#7]
I could be missing something here, but it seems to me that the start() function is never called and therefore toobusy never starts monitoring unless one specifically sets interval with a call such as:

`toobusy.interval(500);`

I am trying to switch from the lloyd/node-toobusy version to this fork. After running
`npm install toobusy-js`
and changing my require statement to
`var toobusy = require('toobusy-js');`
I was unable to get any lag values other than 0. After a little digging it seems to me that if you don't call
interval with an explicit value  start() is never called.

**Comment by STRML** [comment]
Yikes, that's a bad one. Snuck in in the latest refactoring and didn't cause any tests to fail. I've hotfixed this and released as `v0.4.1`, working out a test strategy now but I wanted to make sure this got out.

**Comment by cruisercohen** [comment]
Thanks!
